#
# PLUGINS OPTIONS
#
portname                  0
dummy                     0
gdbstub                   0
hiscore                   0
autofire                  0
data                      1
vector                    0
inputmacro                0
cheatfind                 0
cheat                     0
console                   0
timer                     0
offscreenreload           0
discord                   0
layout                    1
timecode                  0
