approval_policy = "on-request"
model_reasoning_effort = "high"
notify = [
    "/Users/matmoran/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
    "turn-ended",
]
sandbox_mode = "workspace-write"

[desktop]
ambient-suggestions-enabled = true
conversationDetailMode = "STEPS_COMMANDS"
followUpQueueMode = "queue"

[features]
js_repl = false

[marketplaces.openai-bundled]
last_updated = "2026-07-16T21:22:16Z"
source = "/Users/matmoran/.codex/.tmp/bundled-marketplaces/openai-bundled"
source_type = "local"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-16T21:21:27Z"
source = "/Users/matmoran/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"
source_type = "local"

[mcp_servers.backend]
args = [
    "https://mcp.melioffice.com/namespaces/backend/mcp",
    "--transport",
    "http",
]
command = "mcp-remote-proxy"

[mcp_servers.genai_code_review]
args = [
    "https://genai-code-review-mcp.melioffice.com/mcp",
    "--transport",
    "http",
]
command = "mcp-remote-proxy"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.91948"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"
CODEX_HOME = "/Users/matmoran/.codex"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives, such as Computer Use, unless the user explicitly mentions an alternative."
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,7abc8b22abade944bcd80135500416c7aee60c0e94290c7d644b54428a0013ab"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/matmoran/.codex"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[projects."/Users/matmoran"]
trust_level = "trusted"

[projects."/Users/matmoran/Documents/Codex/2026-07-16/como"]
trust_level = "trusted"

[projects."/Users/matmoran/Downloads"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/Meli/models"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/Meli/wiki"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/Notes"]
trust_level = "trusted"

[projects."/Users/matmoran/nixos"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.6-sol" = 1
