approval_policy = "on-request"
model_reasoning_effort = "high"
notify = [
    "/Users/matmoran/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
    "turn-ended",
]
sandbox_mode = "workspace-write"
model = "gpt-5.6-sol"
plan_mode_reasoning_effort = "high"

[desktop]
ambient-suggestions-enabled = true
conversationDetailMode = "STEPS_COMMANDS"
followUpQueueMode = "queue"

[features]
js_repl = false

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/matmoran/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/matmoran/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.tech-plugins-marketplace]
last_updated = "2026-09-10T16:44:32Z"
last_revision = "5d3375e110daa93f6620ce4807866a104c37ad0f"
source_type = "git"
source = "https://github.com/melisource/fury_tech-plugins-marketplace.git"

[mcp_servers.backend]
command = "mcp-remote-proxy"
args = ["https://mcp.melioffice.com/namespaces/backend/mcp", "--transport", "http"]

[mcp_servers.genai_code_review]
command = "mcp-remote-proxy"
args = ["https://genai-code-review-mcp.melioffice.com/mcp", "--transport", "http"]

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/matmoran/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/matmoran/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "0"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.825.51511"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/matmoran/.codex/plugins/cache/openai-bundled/browser/26.825.51511/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.mcp-dataflow-prod-scope]
command = "mcp-remote-proxy"
args = ["https://dataflow-mcp.melioffice.com/mcp", "--transport", "http"]

[mcp_servers.mcp-dataflow-prod-scope.tools.update_job_step]
approval_mode = "approve"

[mcp_servers.mcp-dataflow-prod-scope.tools.execute_job]
approval_mode = "approve"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.cua_repl]
command = "/Applications/ChatGPT.app/Contents/MacOS/ChatGPT"
enabled = false

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."grid-sharing@tech-plugins-marketplace"]
enabled = true

[projects."/Users/matmoran"]
trust_level = "trusted"

[projects."/Users/matmoran/Documents/Codex/2026-07-16/como"]
trust_level = "trusted"

[projects."/Users/matmoran/Downloads"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/Meli/models"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/Meli/wiki"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/Notes"]
trust_level = "trusted"

[projects."/Users/matmoran/nixos"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/UBA/Causalidad"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/UBA/ReinforcementLearning"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/Meli/budget"]
trust_level = "trusted"

[projects."/Users/matmoran/Repos/UBA/ModeladoContinuo"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.6-sol" = 1

[hooks.state."bigquery-meli@workspace-directory:hooks/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:5fd44a27614c12b2fb0e2d173b9085413c7d2bf3324e381e671dfd3fcc004df1"

[hooks.state."conversational-analytics@workspace-directory:hooks/hooks.json:permission_request:0:0"]
trusted_hash = "sha256:aa4581a3790f62b215b0b5eff12a13fed66c3eba4685201d4add141c1c45b205"

[hooks.state."rag@workspace-directory:hooks/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:286cf4bbb02b135f21ad271c00212ad7e7369fb7b79e0b569fcb9e2222236128"
